# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
                ('stav', models.BooleanField()),
                ('cas', models.DateTimeField(blank=True, null=True)),
                ('poznamka', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=50)),
                ('casZacatek', models.DateTimeField()),
                ('casKonec', models.DateTimeField()),
                ('poznamka', models.TextField(blank=True)),
                ('pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='svetlo.GpioModel')),
            ],
        ),
    ]
